### ISSUE TITLE
Archive & Hydrate failures getting OpenSSL.SSL.SysCallError: (104, 'ECONNRESET') by Twitter

### ISSUE THREAD

**Issue by remagio** [edsu/twarc#72]
It's a few weeks that very often Archive.py and Twarc --Hydrate failes unnoticed when launching with &. It doesn't write any traceback neither forwarding output to files. But launching both interactively I get this:

```
Traceback (most recent call last):
  File "/usr/local/bin/twarc.py", line 4, in <module>
    __import__('pkg_resources').run_script('twarc==0.3.0', 'twarc.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1649, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.0-py2.7.egg/EGG-INFO/scripts/twarc.py", line 335, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.0-py2.7.egg/EGG-INFO/scripts/twarc.py", line 109, in main
    
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.0-py2.7.egg/EGG-INFO/scripts/twarc.py", line 298, in hydrate
    
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.0-py2.7.egg/EGG-INFO/scripts/twarc.py", line 172, in new_f
    
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.0-py2.7.egg/EGG-INFO/scripts/twarc.py", line 323, in post
    
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyOpenSSL-0.14-py2.7.egg/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/dist-packages/pyOpenSSL-0.14-py2.7.egg/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
```
The systems used have no I/O issues or network issues, all debians & OS X full updated and Twarc is current v0.3.0. How can I help in finding any solution?

**Comment by remagio** [comment]
*Addendum*: Archive.py & Hydrate python process exit immediately when it happens

*Feature request*: does it require to implement an error.log to get trace of this kind of error when running on background without using 'screen' or 'tmux'?

**Comment by edsu** [comment]
So are you seeing this error when using utils/archive.py ?

**Comment by edsu** [comment]
Can you upgrade to v0.3.1 and see if that fixes your hydrate problem? It did look like the exception handling I added previously wasn't around the post that is only used by --hydrate.

20cb45af1cfc51a87ec3f8d7dbdcd62421bb6614

**Comment by remagio** [comment]
Thx @edsu I'm launching an hydrate now. I'll udpate you asap.

x archive.py I don't have a saved trace of it, but it looks the same for sure the ending part of the hydrate trace for sure.

**Comment by remagio** [comment]
Same error still come up, if it helps it raise up always when starting again the hydrate after a "rate limit exceeded" wait.

**Comment by edsu** [comment]
Mod you have the stack trace?

**Comment by remagio** [comment]
Sorry @edsu but for a mistake I lost it... I scheduled some more iterations of hydrate, more details asap

**Comment by remagio** [comment]
```
2015-07-04 21:22:16,451 WARNING rate limit exceeded: sleeping 833.548175097 secs
Traceback (most recent call last):
  File "/usr/local/bin/twarc.py", line 4, in <module>
    __import__('pkg_resources').run_script('twarc==0.3.1', 'twarc.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1649, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.1-py2.7.egg/EGG-INFO/scripts/twarc.py", line 340, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.1-py2.7.egg/EGG-INFO/scripts/twarc.py", line 109, in main
    
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.1-py2.7.egg/EGG-INFO/scripts/twarc.py", line 298, in hydrate
    
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.1-py2.7.egg/EGG-INFO/scripts/twarc.py", line 172, in new_f
    
  File "/usr/local/lib/python2.7/dist-packages/twarc-0.3.1-py2.7.egg/EGG-INFO/scripts/twarc.py", line 324, in post
    
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyOpenSSL-0.14-py2.7.egg/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/dist-packages/pyOpenSSL-0.14-py2.7.egg/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
```

**Comment by edsu** [comment]
Oh interesting. I'm just noticing now that you are getting a OpenSSL.SSL.SysCallError not a requests.exceptions.ConnectionError ; I guess I can catch that too.

For some context https://github.com/kennethreitz/requests/issues/2543

**Comment by edsu** [comment]
@remagio what version of requests do you have installed? One way to find out is:

```python
% python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__version__
'2.7.0
```

**Comment by remagio** [comment]
It's weird but requests version is '2.6.0', I think it's related with other dependencies not directly with requests. Does it call ssl via urllib remapping via urllib.request to use recent ssl lib ?
urllib.__version__ = '1.17'
urllib3.__version__ = '1.10.2'

**Comment by edsu** [comment]
Can you try to upgrade to latest requests (2.7.0) and test again?

**Comment by remagio** [comment]
Yes, I confirmed the upgrade in previous comment and hydrate is running!

**Comment by remagio** [comment]
@edsu in my experience only a few months ago I didn't get any problem in running multiple hydrate daily. But in your experience: does it mean that people could get in trouble with --hydrate if I upload current IDS sets to Archive.org?

**Comment by edsu** [comment]
Why don't you upload them so I can test with them? I used twarc to hydrate 15 million tweets with no problem a few months ago.

**Comment by remagio** [comment]
Waiting anyway for a solutions about ""this"" issue (hydrate->request->urlib3->pyopenssl<-Twitter), having to hydrate weekly something, I'll do.
When ready with a post describing it I'll upload the ids archive and I'll email you.

**Comment by edsu** [comment]
I believe if you remove pyOpenSSL from your python environment things will just work, if you are looking for a workaround.

**Comment by edsu** [comment]
@remagio would you be able to test this fix I have on the pyopenssl branch? It should catch these pyopenssl errors that aren't being wrapper properly by requests and urllib3.

**Comment by remagio** [comment]
@edsu I submitted the job, feedbacks asap!

**Comment by edsu** [comment]
Given the radio silence it sounds like it might be working longer?

**Comment by remagio** [comment]
Haha, not really there were some other nightly scheduled stuff I forgot to stop. Switched to a dedicated instance for testing b/c it require ~15-~18 hours to hydrate. Relaunched this late morning local time.

**Comment by remagio** [comment]
@edsu it works fine, almost with sets of 750k IDS.

**Comment by edsu** [comment]
Yay!

**Comment by remagio** [comment]
@edsu the branch you released for this issue worked fine till now. If you merge it to master you could close this issue too

**Comment by edsu** [comment]
Thanks for the reminder!
